#!/bin/bash
#SBATCH -p medium # Partition to submit to\n")
#SBATCH -n 1 # Number of cores requested\n")
#SBATCH -N 1 # Ensure that all cores are on one machine\n")
#SBATCH -t 1140 # Runtime in minutes\n")
#SBATCH --mem=10280 # Memory per cpu in MB (see also --mem-per-cpu)\n")
#SBATCH -o hostname_%A_%a.out # Standard out goes to this file\n")
#SBATCH -e hostname_%A_%a.err # Standard err goes to this filehostname\n")

source activate nrrd_env
python /data/project/thymelab/ImagingAnalysis/nrrd_analysis_test_space/evaluate_nrrd_registration.py /data/project/thymelab/ImagingAnalysis/2022-10-12/smoothedtiffs

