#!/bin/bash
#SBATCH -p short # Partition to submit to\n")
#SBATCH -n 12 # Number of cores requested\n")
#SBATCH -N 1 # Ensure that all cores are on one machine\n")
#SBATCH -t 720 # Runtime in minutes\n")
#SBATCH --mem=10280 # Memory per cpu in MB (see also --mem-per-cpu)\n")
#SBATCH -o hostname_%A_%a.out # Standard out goes to this file\n")
#SBATCH -e hostname_%A_%a.err # Standard err goes to this filehostname\n")

rm -dr Rosetta_Code_copy_2
