#!/bin/bash
#SBATCH -p long # Partition to submit to\n")
#SBATCH -n 12 # Number of cores requested\n")
#SBATCH -N 1 # Ensure that all cores are on one machine\n")
#SBATCH -t 3000 # Runtime in minutes\n")
#SBATCH --mem=128000 # Memory per cpu in MB (see also --mem-per-cpu)\n")
#SBATCH -o hostname_%A_%a.out # Standard out goes to this file\n")
#SBATCH -e hostname_%A_%a.err # Standard err goes to this filehostname\n")

./test/run.py -d /data/project/thymelab/running_Rosetta/ari_work/Rosetta_Code/main/database --mode=debug -j 8
