#!/bin/bash
#SBATCH -p long # Partition to submit to
#SBATCH -n 22 # Number of cores requested
#SBATCH -N 1 # Ensure that all cores are on one machine
#SBATCH -t 8640 # Runtime in minutes
#SBATCH --mem=1000 # Memory per cpu in MB (see also --mem-per-cpu)
#SBATCH -o hostname_%A_%a.out # Standard out goes to this file
#SBATCH -e hostname_%A_%a.err # Standard err goes to this filehostname
pbzip2 -d -k -v Enamine_REAL_lead-like_SDF.sdf.bz2

