#!/bin/bash
#SBATCH -p long # Partition to submit to
#SBATCH -n 1 # Number of cores requested
#SBATCH -N 1 # Ensure that all cores are on one machine
#SBATCH -t 3000 # Runtime in minutes
#SBATCH --mem=3000 # Memory per cpu in MB (see also --mem-per-cpu)
#SBATCH -o submit.out # Standard out goes to this file
#SBATCH -e submit.err # Standard err goes to this filehostname
python submit_job.py ari_db_2.job

python submit_job.py ari_db_3.job
